### ISSUE TITLE
Cannot access files in subdirectories

### ISSUE THREAD

**Issue by atty303** [zen-fs/archives#7]
```ts
    const rootZip = await fetch(`https://pob-web-asset.atty303.ninja/versions/v2.42.0/root.zip`);
    await zenfs.configure({
      mounts: {
        "/root": {
          backend: Zip,
          data: await rootZip.arrayBuffer(),
          name: "root.zip",
        },
      },
    });

    console.log(await zenfs.promises.exists("/root/.image.tsv")); // --> This is root file, return true
    console.log(await zenfs.promises.exists("/root/lua/xml.lua")); // --> This is file in directory, return false
    console.log(await zenfs.promises.exists("/root/lua")); // --> This is directory, return false
```

After a little debugging, it seems that the reason is that there is no entry for the subdirectory itself in `ZipFS.entries`.

**Comment by dr-vortex** [comment]
Yet another problem

This makes sense since the ZIP file does not keep track of files. I will get a comprehensive fix released in a few minutes.

**Comment by dr-vortex** [comment]
@atty303 [v0.4.5](https://github.com/zen-fs/zip/releases/tag/v0.4.5) will hopefully be the last release needed to fix all of these issues.

**Comment by atty303** [comment]
Yes, I can confirm that the ZipFS problem has been fixed.
